<?php
session_start();
include "../../render/connection.php";

// Get the ID of the person creating the account (the Admin)
$current_user_id = $_SESSION['user_id'] ?? 0; 

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    
    // Sanitize and collect user input
    $first_name = htmlspecialchars(trim($_POST['first_name']));
    $last_name  = htmlspecialchars(trim($_POST['last_name']));
    $username   = htmlspecialchars(trim($_POST['username'])); // Now generated by JS
    $email      = filter_var($_POST['email'], FILTER_SANITIZE_EMAIL);
    $role       = htmlspecialchars(trim($_POST['role']));
    $phone      = htmlspecialchars(trim($_POST['phone'] ?? ''));
    $password   = $_POST['password']; // Now generated by JS

    // Basic validation (Removed confirm_password check)
    if (empty($first_name) || empty($last_name) || empty($username) || empty($email) || empty($role) || empty($password)) {
        die("Error: Please fill in all required fields.");
    }

    // Validate email format
    if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
        die("Error: Invalid email format.");
    }
    
    $hashed_password = password_hash($password, PASSWORD_BCRYPT);

    // --- Role ID Generation Logic ---
    function getRoleConsonants($role) {
        $consonants_only = preg_replace('/[aeiou\s]/i', '', $role);
        $code = strtoupper(substr($consonants_only, 0, 3));
        while (strlen($code) < 3) { $code .= 'X'; }
        return $code;
    }

    $role_code = getRoleConsonants($role); 
    $current_month = date('m');
    $current_year  = date('Y');

    // Fetch the last ID to continue sequence
    $stmt_last_id = $pdo->query("SELECT user_id FROM users ORDER BY user_id DESC LIMIT 1");
    $last_user = $stmt_last_id->fetch();
    $next_sequence_number = ($last_user) ? $last_user['user_id'] + 1 : 1;
    $sequence_part = str_pad($next_sequence_number, 3, '0', STR_PAD_LEFT);

    $final_role_id = $role_code . $current_month . $current_year . $sequence_part;

    // --- DATABASE TRANSACTION START ---
    try {
        $pdo->beginTransaction();

        // 1. Insert User Data
        $sql = "INSERT INTO users (role_id, first_name, last_name, username, email, phone, role, password, status) 
                VALUES (:role_id, :first_name, :last_name, :username, :email, :phone, :role, :password, 'active')";
        
        $stmt = $pdo->prepare($sql);
        $stmt->execute([
            'role_id'    => $final_role_id,
            'first_name' => $first_name,
            'last_name'  => $last_name,
            'username'   => $username,
            'email'      => $email,
            'phone'      => $phone,
            'role'       => $role,
            'password'   => $hashed_password
        ]);

        // Get the ID of the user just inserted
        $new_user_db_id = $pdo->lastInsertId();

        // 2. Prepare Log Data
        $log_details = "User Created: $username | Role: $role | Name: $first_name $last_name | SysID: $final_role_id";

        // 3. Insert into system_audit_logs
        $log_sql = "INSERT INTO system_audit_logs (table_name, record_id, action_type, old_value, new_value, changed_by) 
                    VALUES ('users', :record_id, 'INSERT', NULL, :new_value, :changed_by)";
        
        $log_stmt = $pdo->prepare($log_sql);
        $log_stmt->execute([
            'record_id'  => $new_user_db_id,
            'new_value'  => $log_details,
            'changed_by' => $current_user_id
        ]);

        $pdo->commit();

        // Redirect with success
        header("Location: ../../web_content/accounts.php?status=success&user=" . urlencode($username));
        exit();

    } catch (Exception $e) {
        if ($pdo->inTransaction()) {
            $pdo->rollBack();
        }
        // Handle duplicate username or email errors gracefully
        if ($e->getCode() == 23000) {
            die("Error: Username or Email already exists.");
        }
        die("Error: Could not create user account. " . $e->getMessage());
    }

} else {
    die("Invalid request method.");
}
?>